### ISSUE TITLE
unresolved import

### ISSUE THREAD

**Issue by ahonorat** [bbodin/turbine#1]
The following error appears when trying to call the example draw_dot.py:
```
Traceback (most recent call last):
  File "Turbine/examples/draw_with_pydot.py", line 21, in <module>
    SDFG.draw_to_pdf("pdfname")  # without .pdf !
  File "/home/ahonorat/Documents/logiciels/sources/turbine/Turbine/graph_classe/dataflow.py", line 73, in draw_to_pdf
    from Turbine.draw.draw_dot import Dot
  File "/home/ahonorat/Documents/logiciels/sources/turbine/Turbine/draw/draw_dot.py", line 2, in <module>
    from Tools.graph_mod.csdf_to_sdf import get_csdf_into_sdf
ImportError: No module named Tools.graph_mod.csdf_to_sdf
```
First, what is draw_dot? Second, what is the Tools module?

Thanks, A. H.

**Comment by YouenL** [comment]
Hi!

The software is no longer maintained and, I think they might be some bugs. Anyway I will look in to it tonight to find out what is your bug.

Envoyé par BlueMail<http://www.bluemail.me/r?b=14013>
Le 30 oct. 2018, à 16:38, Honorat <notifications@github.com<mailto:notifications@github.com>> a écrit:

The following error appears when trying to call the example draw_dot.py:

Traceback (most recent call last):
  File "Turbine/examples/draw_with_pydot.py", line 21, in <module>
    SDFG.draw_to_pdf("pdfname")  # without .pdf !
  File "/home/ahonorat/Documents/logiciels/sources/turbine/Turbine/graph_classe/dataflow.py", line 73, in draw_to_pdf
    from Turbine.draw.draw_dot import Dot
  File "/home/ahonorat/Documents/logiciels/sources/turbine/Turbine/draw/draw_dot.py", line 2, in <module>
    from Tools.graph_mod.csdf_to_sdf import get_csdf_into_sdf
ImportError: No module named Tools.graph_mod.csdf_to_sdf


First, what is draw_dot? Second, what is the Tools module?

Thanks, A. H.

**Comment by bbodin** [comment]
Hi everyone, 

Was funny to see some activity here so I decided to fix the bug! Hope you don't mind.
So some of the files are not consistent between the examples and the libraries, I fixed this particular bug, not sure what other issue can be seen, I will write some testing functions. 
Now you can run draw_with_dot and a file pdfname.pdf should be created.

```
shell> PYTHONPATH=`pwd` python  ./Turbine/examples/draw_with_pydot.py
###### Setup the SDF generation #####
###### Generate dataflow ############
####### Draw File ###################
Name: Test_of_SDF
Graph Properties: dag, not reentrant, not multi-graph
Task count: 10, Arc count: 11
Tot initial marking: 0
Graph type: SDF
```


@ahonorat : if you are looking for something specific, don't hesitate to contact me by mail, I should be able to help. To reply to your questions this draw_dot generates a pdf drawing of the current graph, and there is no Tool module, this was legacy should have been commented.

Best wishes,
Bruno
